import {Platform, StyleSheet} from 'react-native';

export default style = StyleSheet.create({
  radioMain: {
    flex: 1,
    justifyContent: 'center',
  },
  radioText: {
    fontSize: 18,
  },
  radio: {
    height: 30,
    width: 30,
    borderWidth: 2,
    borderRadius: 15,
    margin: 10,
  },
  radioWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioBg: {
    backgroundColor: 'gray',
    height: 20,
    width: 20,
    borderRadius: 10,
    margin: 3,
  },
  main: {
    flex: 1,
  },
  box1: {
    flex: 1,
    backgroundColor: '#0A8A4A',
    flexDirection: 'row',
  },
  box2: {
    flex: 1,
    backgroundColor: '#5EDC9D',
    flexDirection: 'row',
  },
  box3: {
    flex: 1,
    backgroundColor: '#68A285',
  },
  innerBox1: {
    flex: 1,
    backgroundColor: '#1D95C1',
    margin: 10,
  },
  innerBox2: {
    flex: 1,
    backgroundColor: '#88B1BF',
    margin: 10,
  },
  innerBox3: {
    flex: 1,
    backgroundColor: '#446673',
    margin: 10,
  },
  innerBox4: {
    flex: 1,
    backgroundColor: '#CAAC26',
    margin: 10,
  },
  innerBox5: {
    flex: 1,
    backgroundColor: '#7F6D16',
    margin: 10,
  },
  innerBox6: {
    flex: 1,
    backgroundColor: '#883535',
    margin: 10,
  },
  innerBox7: {
    flex: 1,
    backgroundColor: '#22CEC7',
    margin: 10,
  },
  innerBox8: {
    flex: 1,
    backgroundColor: '#0B5250',
    margin: 10,
  },
  innerBox9: {
    flex: 1,
    backgroundColor: '#00FFF5',
    margin: 10,
  },

  grid: {
    fontSize: 25,
    backgroundColor: '#577D6A',
    width: 110,
    height: 110,
    textAlign: 'center',
    textAlignVertical: 'center',
    margin: 10,
    color: '#DAE2DE',
    borderRadius: 10,
  },
  text: {
    fontSize: 25,
  },
  view: {
    margin: 10,
  },
  textInput: {
    borderWidth: 2,
    borderRadius: 5,
    borderColor: 'lightgray',
    margin: 5,
    padding: 10,
  },
  list: {
    color: 'black',
    backgroundColor: 'lightgray',
    margin: 5,
    padding: 20,
    borderRadius: 5,
    fontSize: 20,
  },

  item: {
    flex: 1,
    fontSize: 14,
    color: '#353535',
    margin: 5,
  },
  box: {
    flexDirection: 'row',
    borderWidth: 2,
    margin: 5,
    borderColor: '#56826C',
  },
  button: {
    color: 'white',
    margin: 10,
    padding: 10,
    borderRadius: 10,
    shadowColor: 'red',
    elevation: 10,
    textAlign: 'center',
    fontSize: 18,
  },
  button_hover: {
    backgroundColor: 'pink',
  },
  success: {
    backgroundColor: 'green',
  },
  warning: {
    backgroundColor: 'orange',
  },
  error: {
    backgroundColor: 'red',
  },
  primary: {
    backgroundColor: 'blue',
  },
  modalOpen: {
    fontSize: 18,
    textAlign: 'center',
    backgroundColor: '#558853',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    color: '#fff',
    shadowColor: '#fff',
    elevation: 10,
  },
  modalWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    backgroundColor: '#fff',
    padding: 40,
    borderRadius: 20,
    shadowColor: '#000',
    elevation: 10,
  },
  modalText: {
    fontSize: 20,
    marginBottom: 10,
  },
  modalClose: {
    fontSize: 18,
    textAlign: 'center',
    backgroundColor: '#6D3205',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    color: '#fff',
    shadowColor: '#fff',
    elevation: 10,
  },
  pressBtn: {
    fontSize: 18,
    backgroundColor: '#0d6f2f ',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    shadowColor: '#000',
    elevation: 10,
    textAlign: 'center',
    color: 'white',
  },
  platformOsText: {
    fontSize: 18,
    color: Platform.OS == 'android' ? '#00582b' : '#005855',
  },
  container: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  openBtn: {
    fontSize: 18,
    textAlign: 'center',
    backgroundColor: 'green',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    shadowColor: '#000',
    elevation: 10,
    color: '#fff',
  },
  modal: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(50,50,50,0.3)',
  },
  modalBody: {
    backgroundColor: '#fff',
    height: 200,
    width: 300,
    justifyContent: 'flex-end',
    borderRadius: 10,
    shadowColor: '#000',
    elevation: 10,
  },
  modalT: {
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'times new roman',
    fontWeight: 700,
  },
  closeBtn: {
    backgroundColor: 'red',
  },
  loginText: {
    fontSize: 18,
    fontWeight: 500,
    margin: 2,
  },
  loginInputText: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    margin: 5,
    fontSize: 14,
  },
  loginFieldView: {
    margin: 10,
  },
  loginBtn: {
    textAlign: 'center',
    backgroundColor: '#40bf80',
    padding: 10,
    borderRadius: 10,
    fontSize: 16,
    fontWeight: 500,
    color: '#fff',
    margin: 5,
  },
  homeContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  homeHeading: {
    fontSize: 24,
    margin: 5,
    color: 'green',
    fontWeight: 800,
    textAlign: 'center',
  },
  homeInfo: {
    margin: 10,
    backgroundColor: 'rgba(70, 70, 70,0.1)',
    borderRadius: 10,
    padding: 10,
  },
  homeText: {
    fontSize: 16,
    fontWeight: 400,
    fontFamily: 'times new roman',
  },
  imageStyle: {
    width: 150,
    height: 150,
    margin: 10,
    borderRadius: 75,
  },
  imageContainer: {
    flex: 1,
    // alignItems: 'center',
  },
  textImage: {
    color: 'white',
    fontSize: 24,
    textAlign: 'center',
    backgroundColor: '#000000c0',
    padding: 10,
    fontWeight: 500,
  },
  imageBg: {
    flex: 1,
    justifyContent: 'center',
  },
  // lable: {
  //   fontSize: 20,
  //   color: 'brown',
  //   marginLeft: 10,
  //   marginTop: 10,
  // },
  // textInput: {
  //   borderWidth: 2,
  //   borderRadius: 10,
  //   borderColor: 'black',
  //   margin: 10,
  //   fontSize: 20,
  //   padding: 10,
  // },
  // textView: {
  //   color: 'white',
  //   backgroundColor: 'gray',
  //   fontSize: 25,
  //   margin: 5,
  //   padding: 10,
  //   borderRadius: 20,
  //   height: 90,
  //   textAlignVertical: 'center',
  // },
  // view: {
  //   // backgroundColor: 'green',
  //   margin: 5,
  //   padding: 5,
  // },
  // text: {
  //   color: 'black',
  //   backgroundColor: 'lightgray',
  //   fontSize: 25,
  //   margin: 5,
  //   padding: 10,
  //   borderRadius: 20,
  //   height: 90,
  //   textAlignVertical: 'center',
  // },
});
